### ISSUE TITLE
能否指点下脚本该如何使用

### ISSUE THREAD

**Issue by mikulolicon** [YomikoR/VapourSynth-Destripe#1]
能不能指点下这个脚本怎么用，我直接套了git的example部分，但是直接报错（descale.py和destripe.py文件已经放到了AppData\Roaming\Python\Python38\site-packages路径下）：
import vapoursynth as vs

from destripe import Destripe

from vapoursynth import core
core.num_threads = 6
core.max_cache_size = 10000

src = core.lsmas.LWLibavSource(source="片源",fpsnum=0,fpsden=1,decoder="")

down = Destripe(src, 1280, 360, kernel='bicubic', b=0, c=1/3, src_top=[1/12, -1/12])
up = core.resize.Bicubic(down, 1920, 1080, filter_param_a=0, filter_param_b=1/3) 

up.set_output()

报错如下：

vapoursynth.Error: Debicubic: Function does not take argument(s) named src_width, src_height

**Comment by YomikoR** [comment]
`src_width` and `src_height` are parameters of descale that are present in the master branch but not included in the released library. The author has no intention to release for them in the near future, so you may manually compile the master branch of descale to use these parameters.

I have made `src_width` and `src_height` optional to descale in https://github.com/YomikoR/VapourSynth-Destripe/commit/7855e1eb1359822c583c84fad8f07e7ba146be4a so that you won't need manual compilation if you don't touch these parameters.
